package exception

object D2 {
  def main(args: Array[String]): Unit = {
    throw new Exception("exception")
  }

}
